### ISSUE TITLE
Shield flips quickly from off-hand to main-hand and back when auto-refilling slot with blocks

### ISSUE THREAD

**Issue by XavierBit** [Siphalor/mouse-wheelie#176] opened 2022-07-17 14:31 UTC
**Version**
Minecraft: 1.19
Mouse Wheelie: mousewheelie 1.10.1 mc1.19-pre1

**Describe the bug**
If placing blocks, preferably non-stackable like shulker boxes on the ground, the off-hand shield flips quickly to the main-hand and goes back instantly. If placing blocks quickly, it can hamper the block placement. 

**To Reproduce**
1. Place shulker boxes repetitively on the ground and watch the shield going back and forth in survival.
2. Shield flips briefly from one hand to the other and back.

**Expected behavior**
Shield should stay in the off-hand.

**Log**
No log entry visible afaik

This only happens on the SMP I'm playing. It appears to be ok in singleplayer with the same configuration.

I was able to make a screenshot (attached) the moment the shield flips to the main-hand. 

![2022-07-17_11 25 53](https://user-images.githubusercontent.com/95314871/179403030-ac11484b-3e75-4123-8718-c19039e21535.png)

Please follow the crashy online log https://crashy.net/5HCQx0KOhIddhqGI7lnW
This crash has been provoked manually and is not related to the problem but gives insight in my mods and general environment.

**Comment by Siphalor** [comment] 2022-07-20 16:50
That's caused by the "Restore selected slot" config in the refill section.
I'd say this is currently working as intended.

To successfully keep the same slot selected, some swapping around is required.
In singleplayer, with the default interaction rate of `1`, you want notice the swapping.
On servers, with the default interaction rate of `10` and some lag, you'll clearly notice it.

---

You may be able to fix it on your end, by decreasing the interaction rate (at least if the server allows that).
Alternatively you can completely turn off "Restore selected slot".

---

I'm not gonna close this issue yet but turn this into a question, since this is basically a subjective consideration:
Should "restore selected slot" be kept on by default?

**Comment by XavierBit** [comment] 2022-07-20 19:35
Thanks for responding, Siphalor!
I disabled the "Restore selected slot" option on the profile and now it works perfectly.

I'm not sure if disabling it will be the solution, maybe an information pop-up when hovering over this option would be clearer?

**Comment by Siphalor** [comment] 2022-07-20 19:42
If you click on the option title, then you'll see a description of it :)

It might still be a bit hidden in the config.
So the general question is still, whether this should be enabled by default.
It might make sense turning it into an opt-in, as someone who want this option will probably go looking for it.
While everyone that stumbles upon this behavior wouldn't be able to deduce it to be this option :thinking: 

I think I'm gonna turn off that option by default in the next-ish release, whenever that'll be ^^

**Comment by haykam821** [comment] 2022-07-20 19:46
Was this option disabled by default or simply not present in previous releases? I haven't seen this issue until recently on Minecraft 1.19.

**Comment by Siphalor** [comment] 2022-07-20 19:51
The feature to keep the currently selected slot focused was introduced in the latest minor release (1.10.0) and is currently enabled by default.

**Comment by haykam821** [comment] 2022-07-20 20:02
I don't see a need to have this option, then. The restock feature as it existed before version 1.10.0 worked fine for my needs.

**Comment by Siphalor** [comment] 2022-07-20 20:16
well, maybe not for you, but this was specifically requested.
Again, I'm just gonna make it disabled by default from now on, so it's gonna be an opt-in.

**Closed as completed** 2022-12-17 14:29 UTC
Labels: question
