### ISSUE TITLE
Crash with 1.2.5 on 1.14.4

### ISSUE THREAD

**Issue by Spazmunki13** [Siphalor/mouse-wheelie#28] opened 2019-07-22 08:44 UTC
I seem to be getting a crash when the game is loading up using the latest version.

Crash Report:
https://paste.ee/p/Tcihi

**Comment by Madis0** [comment] 2019-07-22 10:27
Might be a duplicate of #27 - get the hotfix version of MW

**Comment by Siphalor** [comment] 2019-07-22 10:30
@Madis0 He's already using the hotfix version - it's a different bug I need to investigate.

**Comment by Siphalor** [comment] 2019-07-22 10:32
It's probably related to [amecs#2](https://github.com/Siphalor/amecs/issues/2)

**Comment by Siphalor** [comment] 2019-07-22 12:31
It should be working now (see [amecs#2](https://github.com/Siphalor/amecs/issues/2)).

**Closed by Siphalor** 2019-07-22 12:31 UTC
Labels: bug

**Comment by Madis0** [comment] 2019-07-24 11:48
Why does MW need amecs in the first place?

**Comment by Siphalor** [comment] 2019-07-25 12:35
@Madis0 It didn't really need it, so I removed it again but I temporarely used it to manage the keybinding for tool picking (since it was shift-middle-click).
