### ISSUE TITLE
[bug] When typing in chat, all key bindings get activated

### ISSUE THREAD

**Issue by Unforgettable14** [Siphalor/mouse-wheelie#37] opened 2019-08-04 14:02 UTC
**Version**
1.14.4
**Describe the bug**
With MW installed, if I open the chat window, the key bindings are still active therefore I see myself moving, jumping and activating other bindings like map related

**To Reproduce**
Install Fabric
Install Mouse Wheelie 
Open chat window and start typing, when using WSAD and space, you move and jump

**Expected behavior**
No background interaction at all

**Log**
The important parts of the log.

**Additional context**

**Comment by Siphalor** [comment] 2019-08-04 16:36
Which version of MW are you using?

This should be fixed at least since 1.2.11

**Comment by tehseano** [comment] 2019-08-13 14:45
Also have the exact same issue. Using MultiMC, Minecraft 1.14.4, no other mods. Can reproduce easily. Removing the mod from the mod folder and starting minecraft vanilla, works normal. Adding the mod and restarting, immediately causes it to happen. Also cannot search the inventory as keys like E and T close the inventory or open the chat, etc.

**Comment by Unforgettable14** [comment] 2019-08-13 15:57
I found that the issue is I downloaded it from 9minecraft and not
curseforge. I've been warned not to download from 9minecraft

**Comment by CJNiiva** [comment] 2019-08-19 14:48
I can reproduce, just have it installed, and you can see that you can walk while typing in chat

**Closed** 2019-09-17 00:51 UTC
Labels: bug, can't reproduce
