### ISSUE TITLE
[feature request] Option to disable item scrolling in the AE2 Terminal

### ISSUE THREAD

**Issue by The-Fireplace** [Siphalor/mouse-wheelie#117] opened 2021-05-29 16:11 UTC
**Is your feature request related to a problem? Please describe.**
When in the Applied Energistics 2 terminal, I'd like to be able to easily scroll through my items without Mouse Wheelie's item scrolling activating

**Describe the solution you'd like**
A config option is added to disable item scrolling in the AE2 Terminal

**Comment by Siphalor** [comment] 2022-02-22 21:16
Well, it seems like I somehow overlooked this before.
AE2 is currently officially unsupported. I looked into their slot system before and there's really nothing I can do without risking my mental sanity.

This is a duplicate of #83

**Closed as completed by Siphalor** 2022-02-22 21:16 UTC
Labels: duplicate, enhancement, wontfix
