### ISSUE TITLE
Game crash while attempting to launch

### ISSUE THREAD

**Issue by RazeABlaze** [Siphalor/mouse-wheelie#183] opened 2022-09-06 18:27 UTC
Minecraft version 1.19.2

Crashes after clicking play on the Minecraft launcher having fabric 1.19.2 selected

Using fabric 1.19.2
add mousewheelie-1.10.2+mc1.19-pre1 to mods folder
upon clicking play get crash report

![unknown](https://user-images.githubusercontent.com/112976738/188710475-58912d58-640d-4fec-bb10-6c492f8b4708.png)

**Comment by Siphalor** [comment] 2022-11-17 19:25
This was caused by some outdated Fabric API modules bundled with Mouse Wheelie.
It will be fixed in the next release, until then you can manually install the latest Fabric API as a workaround.

**Closed as completed by Siphalor** 2022-11-17 19:26 UTC
Labels: bug
